name: Docker Image CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login dockerhub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.USERNAME_DOCKERHUB}}
          password: ${{secrets.PASSWORD_DOCKERHUB}}

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.USER_DOCKERHUB}}/evunodevopz:latest

      - name: push dockerhub
        run: docker push ${{secrets.USER_DOCKERHUB}}/evunodevopz:latest

